name: "Build in devenv"

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        target: [mqtt, monitor]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install --accept-flake-config tarball+https://install.devenv.sh/latest
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci

      - name: Run a single command in the devenv shell
        run: devenv shell build ${{ matrix.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.target }}
          path: .pio/build/${{ matrix.target }}/firmware.*
